### PR TITLE
Jnm skel profile card

### PR DESCRIPTION
**Pull request by Jess-Morrison**

### CODE REVIEW

**Review by emilyjstroud — APPROVED** [review]
love those comments girl

**Review by Massacre-Saint — CHANGES_REQUESTED** [review]
Needs to add /  to  main.css and main.js

**Review by acceleratedMbaDev — CHANGES_REQUESTED** [review]
need to put / before main.css and main.js to come out of the folder please :)

**Review by acceleratedMbaDev — APPROVED** [review]
looks good

**Review by Massacre-Saint — APPROVED** [review]
Looks great!!!!

**Pull request merged**
